HW2
alexs6669/js_basics pull request #2
Opened 2021-01-24 10:41 UTC by alexs6669

2021-01-24 18:42 UTC, Om1X requested changes

2021-01-24 18:42 UTC, Om1X commented on HW2.js
> +}
В задании четко сказано, что у функций должно быть 2 параметра. Никакого запроса данных внутри функций не должно быть.

2021-01-24 18:42 UTC, Om1X commented on HW2.js
> +}
соответственно это задание сделано также неверно

2021-01-25 14:35 UTC, Om1X requested changes

2021-01-25 14:35 UTC, Om1X commented on HW2.js
>  }
Уже почти как нужно. Но все еще лини код имеется. Этот код лишний:
```javascript
arg1 = parseInt(prompt('Введите первое число: '))
arg2 = parseInt(prompt('Введите второе число: '))
```
По факту должно быть так:
```javascript
return arg1 + arg2;
```

По аналогии делаем так со всеми функциями.

2021-01-25 15:40 UTC, alexs6669 commented on HW2.js
>  }
Артем, все, вроде теперь должно быть верно.) Очень неловко заваливаться на такой простой задаче. 
Заморочился с интерактивностью, и почему-то хотелось, чтобы функции из 5го задания отрабатывали отдельно от 6го задания без подстановки.

2021-01-27 15:04 UTC, Om1X approved these changes

2021-01-27 16:38 UTC, closed without merging