HW4
alexs6669/js_basics pull request #4
Opened 2021-01-31 11:56 UTC by alexs6669

Первое задание получилось через кривоватый конструктор, вывод норм, но если честно до конца так и не врубился что к чему=)

По второму заданию использовал объекты и в прошлом ДЗ, поэтому оставил предыдущую реализацию.
В пункте 2.1 - объекты - это товары, корзина - все же массив объектов, т.к. это показалось логичным.

2021-02-04 08:27 UTC, alexs6669 commented
Решение первого задания оказалось гораздо проще чем я думал, но решил все же идти до конца=) добил проверку на ввод отрицательного числа и любого не числа. Также добавил подсчет количества товаров в корзине.

2021-02-06 15:13 UTC, Om1X requested changes

2021-02-06 15:13 UTC, Om1X commented on HW4.js
> +console.log(new NumToObj(-10))
конструкторы тут лишние, мы их и не изучали, но результат есть, только с оверинжинирингом.

2021-02-06 15:13 UTC, Om1X commented on HW4.js
> +}
здесь нужно было объединить все в один объект со свойством, в котором будет свойство с массивом товаров и метод подсчета.

2021-02-09 20:38 UTC, Om1X approved these changes

2021-02-10 16:33 UTC, closed without merging