HW6
alexs6669/js_basics pull request #7
Opened 2021-02-09 07:25 UTC by alexs6669

2021-02-09 21:25 UTC, Om1X requested changes

2021-02-09 21:25 UTC, Om1X commented on catalog+cart.js
> +        const good = catalog.find(id_product)
почему `const good = catalog.find(id_product)` а не `const good = this.goods.find(id_product)`

2021-02-09 21:25 UTC, Om1X commented on catalog+cart.js
> +            cart.addToCart(good)
лучше создать свойство cart внутри объекта catalog и в него сохранить ссылку на объект корзины, чтобы по коду завязываться только на this.cart а не на внешние данные.

2021-02-09 21:25 UTC, Om1X commented on catalog+cart.js
> +            : (this.goods[this.goods.length] = { ...good, quantity: 1 })
1. Вы уже использовали find выше, почему не сделали и тут? Так Вы сразу получаете либо элемент или null
2. Терновник тут не к месту.
3. Конструкция `(this.goods[this.goods.length] = { ...good, quantity: 1 })` очень грубая. Есть метод push(), его и пользуем.

2021-02-11 07:28 UTC, alexs6669 commented
отработал замечания

2021-02-24 14:51 UTC, Om1X requested changes

2021-02-24 14:51 UTC, Om1X commented on catalog+cart.js
> +    init() {
в init добавить параметр cart `init(cart) {}`

2021-02-24 14:51 UTC, Om1X commented on catalog+cart.js
> +catalog.init()
`catalog.init(cart)`

2021-02-24 14:51 UTC, Om1X commented on catalog+cart.js
> +    },
эта конструкция не нужна

2021-02-24 14:51 UTC, Om1X commented on catalog+cart.js
> +    init() {
можем после спокойно записать так `this.cart = cart`

2021-02-24 15:21 UTC, closed without merging